services:
  - type: worker
    name: db-writer
    env: go
    startCommand: ./app
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app
    envVars:
      - key: CONN_STRING
        sync: false
